### ISSUE TITLE
MediaStore.Images.Media.MIME_TYPE问题

### ISSUE THREAD

**Issue by jiaoyongzhi** [caocao123/android10DownFile#1]
downMusicVideoPicFromService 这个方法的 inserType.equals(DIRECTORY_PICTURES) 判断里将contentValues.put(MediaStore.Images.Media.MIME_TYPE, “image/jpeg”);替换为contentValues.put(MediaStore.Images.Media.MIME_TYPE, getMIMEType(fileName));比较好

有的图片是image/jpeg 的  但是下载保存失败  这是个问题

**Comment by CMzhizhe** [comment]
这个下载 image/jpeg  格式的，我不知道怎么下。
不过这个方案好 contentValues.put(MediaStore.Images.Media.MIME_TYPE, getMIMEType(fileName));比较好，等会我会改下
