### ISSUE TITLE
关于魅族7.

### ISSUE THREAD

**Issue by jiaoyongzhi** [caocao123/android10DownFile#6]
我在downMusicVideoPicFromService这个方法里加了  if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
                        String[] proj = {MediaStore.Images.Media.DATA};
                        Cursor actualimagecursor = context.getContentResolver().query(uri, proj, null, null, null);
                        int actualImageColumnIndex = actualimagecursor.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
                        actualimagecursor.moveToFirst();
                        String imgPath = actualimagecursor.getString(actualImageColumnIndex);
                        context.sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(new File(imgPath))));
                    }
加了这个判断

不过用MediaScannerConnection   你用的这个更好一点

**Comment by CMzhizhe** [comment]
就用我这个吧，这个好些
